import { Router } from "express";
const router = Router();
import categoryRouter from "./category/router";
import tourRouter from "./tours/router";
import authorRouter from "./author/router";
import videosRouter from "./videos/router";
import complex_categoryRouter from "./complex_categorys/router";
import complexRouter from "./complex/router";
import blogRouter from "./blog/router";
import newsRouter from "./news/router";
import ordersRouter from "./orders/router";
router.use("/category", categoryRouter);
router.use("/tour", tourRouter);
router.use("/author", authorRouter);
router.use("/video", videosRouter);
router.use("/complex_category", complex_categoryRouter);
router.use("/complex", complexRouter);
router.use("/blog", blogRouter);
router.use("/news", newsRouter);
router.use("/order", ordersRouter);
export default router;
